sprint_3
atkachev/architecture-sprint-3 pull request #1
Opened 2024-11-23 20:47 UTC by atkachev

первая часть, задание 1,2,3

2024-11-24 11:57 UTC, dchekushin requested changes

2024-11-24 11:57 UTC, dchekushin commented on diagrams/task1/task1_context.puml
> +Person(specialist, "Specialist", "Подключение к системе")
Стоит выделить мобильное приложение или веб-сайт отдельным контейнером. Пользователи взаимодействуют именно с ними

2024-11-24 11:57 UTC, dchekushin commented on diagrams/task1/task1_context.puml
> +Rel(SmartHomeSystem,sensor, "Вкл/выкл, актуальная температура")
Укажите протоколы и технологии взаимодействия (HTTP и т.д.) между контейнерами.

2024-11-24 11:57 UTC, dchekushin commented on diagrams/task1/task1_context.puml
> +System(SmartHomeSystem, "Теплый дом", "Система организует удалённое управление отоплением в доме")
Укажите технологии (язык программирования, СУБД и т.д.) используемые в монолите.

2024-11-24 11:57 UTC, dchekushin commented on diagrams/task1/task1.txt
> +На этом уровне мы покажем основные взаимодействия системы Теплый дом с внешними пользователями и системами. На диаграмме контекста нужно показать такие элементы:
1. Распишите подробнее функциональность монолитного приложения.
2. Проанализируйте архитектуру монолитного приложения.
3. Определите домены и границы контекстов. Например, домен «Управление Устройствами».
4. Подробно опишите, какие проблемы создаёт монолитного решение для компании в контексте текущих бизнес-задач.

2024-11-24 11:57 UTC, dchekushin commented on diagrams/task2/to_be/task2_to_be.txt
> +    Пользователь -> Дом | one to many
Несколько пользователей могут иметь доступ к одному дому, а один пользователь — к нескольким домам.

2024-11-24 11:57 UTC, dchekushin commented on diagrams/task2/to_be/task2_to_be.txt
> +запуск сценариев микросервиса по расписанию.
Еще можем добавить сервис автоматизации, что бы пользователи могли настраивать автоматические сценарии работы устройств.

2024-11-24 11:57 UTC, dchekushin commented on diagrams/task2/to_be/task2_to_be.txt
> +Все обращение пользователя идут через Api Gateway по REST, от фронта. Kafka не используется.
Выглядит как - будто все четыре сервиса выполняют за одну и туже функцию - управление устройствами. Может объединим?

2024-11-24 11:57 UTC, dchekushin commented on diagrams/task2/to_be/task2_to_be.txt
> +Микросервисы:
Подумайте, возможно стоит добавить домены, такие как "Телеметрия" и "Управление домами" ?

2024-11-24 11:57 UTC, dchekushin commented on diagrams/task2/to_be/task2_to_be.txt
> +Взаимодействия между микросервисами нету. Каждый микросервис имеет свои сценарии,
Если добавим асинхронное взаимодействие между некоторыми сервисами через  Kafka, можем уменьшить нагрузку на сервисы и ускорим общее время отклика системы на запросы пользователей и устройств.

2024-11-24 21:40 UTC, atkachev commented on diagrams/task2/to_be/task2_to_be.txt
> +Взаимодействия между микросервисами нету. Каждый микросервис имеет свои сценарии,
Можете написать более детально между какими сервисами из моего решения мне нужно добавить взаимодействия через Kafka. Например изначальный api у нас не меняется для света, какой метод из этого api будет работать быстрее и за счет чего? 
Пока я вижу что kafka в моем решение не нужна. Если нужно масштабироваться то увеличиваем количество backend серверов, если нам нехватает объема бд то шардируемся. В данной задаче у нас есть датчик которым пользуется очень органиченое количество людей, т е на один дом я не ожидаю что будет больше чем 20(100) датчиков. 
Пользователь вызывает ручку дай текущую температуру он ожидает что он ее получит тут же и самую актуальную, т е мы в любом случае сходим за данными на датчик тут же. 

У меня нету никаких предубеждений насчет очередей, но в текущем описание задачи я не вижу в какое место ее можно добавить, чтобы получить решение лучше того что сейчас есть. Я не додумал сценарий в котором бы ее применить по делу, в тех предположениях чтобы были описаны явно, очередь ничего не дает если мы ее противопоставляем Rest-у.

2024-11-24 21:40 UTC, atkachev commented on diagrams/task1/task1_context.puml
> +Person(specialist, "Specialist", "Подключение к системе")
Добавил и мобильное приложение. WebApp есть начиная с уровня container(файл  task1_container.puml). в уровень context не добавлял как в уроке было.

2024-11-24 21:40 UTC, atkachev commented on diagrams/task1/task1_context.puml
> +Rel(SmartHomeSystem,sensor, "Вкл/выкл, актуальная температура")
Добавил протоколы на уровень контейра, файл task1_container.puml

2024-11-24 21:40 UTC, atkachev commented on diagrams/task1/task1_context.puml
> +System(SmartHomeSystem, "Теплый дом", "Система организует удалённое управление отоплением в доме")
Добавлены в файле  task1_container.puml. Кода веба и мобильного нету сделал предположения что react-web, kotlin, swift - mobile App

2024-11-24 21:40 UTC, atkachev commented on diagrams/task1/task1.txt
> +На этом уровне мы покажем основные взаимодействия системы Теплый дом с внешними пользователями и системами. На диаграмме контекста нужно показать такие элементы:
Добавил ответы в task1.txt

2024-11-24 21:40 UTC, atkachev commented on diagrams/task2/to_be/task2_to_be.txt
> +    Пользователь -> Дом | one to many
Изменил; в задание не было явно указаны ограничения.

2024-11-24 21:40 UTC, atkachev commented on diagrams/task2/to_be/task2_to_be.txt
> +запуск сценариев микросервиса по расписанию.
Метод автоматизации добавил для каждого своего микросервиса в класс *ScenarioService. 
Например:
task2_code_scenario_to_be.puml
HeatingService -микросервис
class HeatingScenarioService {
    +void scheduledAllScenaries() //запуск всех задач по их расписанию
}
В каждом моем микросервисе запускаются собственные сценарии по расписанию, аналогично коду выше.

2024-11-24 21:40 UTC, atkachev commented on diagrams/task2/to_be/task2_to_be.txt
> +Все обращение пользователя идут через Api Gateway по REST, от фронта. Kafka не используется.
В моем решение монолит разбивается по назначению умного устройства: свет, видео, ворота и т д 
Каждая из сущностей имеет свои особенности, разные версии устройств, разные сценарии. Например в видео я предполагаю что будет хранится видео, и проще чтобы одна команда разбиралась с этими тонкостями.

2024-11-24 21:40 UTC, atkachev commented on diagrams/task2/to_be/task2_to_be.txt
> +Микросервисы:
В моем решение пользователь заходит в ЛК видет список своих устройств и для каждого из них может назначить сценарий. Исходя из описания задачи и предоставленного изначального апи и решения пользователь синхронно вызов сервис/api дай мне текущую температуру и получает ответ. Выделять данный  один вызов в домен "Телеметрия" не вижу смысла.

2024-11-24 21:50 UTC, merged

2024-11-24 21:56 UTC, atkachev commented on diagrams/task2/to_be/task2_to_be.txt
> +Взаимодействия между микросервисами нету. Каждый микросервис имеет свои сценарии,
@dchekushin https://github.com/atkachev/architecture-sprint-3/pull/2 случайно закрыл данный pr, создал новый.

2024-11-25 21:40 UTC, dchekushin commented on diagrams/task2/to_be/task2_to_be.txt
> +Все обращение пользователя идут через Api Gateway по REST, от фронта. Kafka не используется.
Решение при котором микросервисы разделены по назначению устройств имеет место. У такого решения в перспективе может возникнуть проблема расширения, Например: добавление нового типа устройств повлечет необходимость доработок как минимум в двух микросервисах

2024-11-25 21:46 UTC, dchekushin commented on diagrams/task2/to_be/task2_to_be.txt
> +Микросервисы:
Посмотрите пожалуйста требование в пункте "2. Целевая экосистема, которую необходимо создать": Система должна предоставить пользователю возможность просматривает телеметрию. Предусмотрите в архитектуре это требование.

2024-11-25 21:47 UTC, dchekushin commented on diagrams/task2/to_be/task2_to_be.txt
> +Взаимодействия между микросервисами нету. Каждый микросервис имеет свои сценарии,
Ничего страшного. Самое главное, что итоговые диаграммы можно просмотреть.

2024-11-25 22:08 UTC, dchekushin commented on diagrams/task2/to_be/task2_to_be.txt
> +Взаимодействия между микросервисами нету. Каждый микросервис имеет свои сценарии,
Асинхронное взаимодействие между микросервисами имеет ряд преимуществ: Например, использование брокера сообщений при сборе телеметрии, позволит развязать сервисы управления устройствами и сервис телеметрии.

В нашей целевой архитектуре сервисы управления устройствами, сбора телеметрии и автоматизированных сценариев могут взаимодействовать асинхронно. Такой подход помогает повысить производительность системы в целом, ускоряя отклик на запросы пользователей и устройств, поскольку взаимодействие между сервисами не блокирует выполнение других операций.

2024-11-25 22:14 UTC, dchekushin commented on diagrams/task3/task3_er.puml
> +@enduml
В общем схема отображает требования к системе, но стоит описать, как планируется организовать хранение данных телеметрии. Например, я иногда смотрю какая была температура у меня дома неделю назад и т.д.

2024-11-26 13:36 UTC, atkachev commented on diagrams/task3/task3_er.puml
> +@enduml
Добавил. HeatingCondition,  GatesCondition и т д. Т е в этих сущностях мы делаем снимок системы в моменте и сохраняем по сценарию-админа в системе.

2024-11-26 13:36 UTC, atkachev commented on diagrams/task2/to_be/task2_to_be.txt
> +Взаимодействия между микросервисами нету. Каждый микросервис имеет свои сценарии,
Согласен, но я посчитал такую модель избыточной в данной задаче. Я не представляю какие данные мне нужно пересылать по кафке.
у меня есть сервис Тепла,  и все что связано с теплом находится в нем. 
Я вижу так, для каждого дома дергаются данные о температуре раз в 30 минут, и записываются в бд. Если одна машина не сможет это сделать, разбить на несколько машин опрос. После того как датчик вернул данные сразу записали в бд. После этого пользователь увидел в ЛК данные если зайдет.

Есть сущность которая как бы хранить данные актуальные сейчас а не в прошлом, нам же надо для телеметрии сохранять снимок данного класса, только убрав часть данных.
class HeatingSystem {
  +Long id
  +boolean isOn
  +Double targetTemperature
  +Double currentTemperature
}

2024-11-26 13:36 UTC, atkachev commented on diagrams/task2/to_be/task2_to_be.txt
> +Микросервисы:
Добавил описание. Схематично отобразил например для темпла: task2_code_scenario_to_be.puml
Администратор системы создает системные сценарии, которые сохраняют информацию по таймингу. После получения данных, сохраняют данные в таблицу, например каждую минуту для дома=houseId, записывается данные в таблицу HeatingCondition. Для просмотре данных в лк вызываем HeatingConditionService.findConditions
HeatingScenarioService.scheduleAllScenaries() - запуск всех задач по расписанию.

2024-11-26 13:49 UTC, atkachev commented on diagrams/task3/task3_er.puml
> +@enduml
@dchekushin Добавил правки в https://github.com/atkachev/architecture-sprint-3/pull/2 
незнаю надо ли еще раз указывать это в яндексе практикум, но отправил запрос.